arr = [' ITO', ' Pragati Maidan', ' ITC Maurya', ' Cyber Hub',
       ' Khan Market', ' Lodhi Colony', ' Sector 15', ' Connaught Place',
       ' Chawri Bazar', ' Kailash Colony', ' Two Horizon Center',
       ' Vijay Nagar', ' Chanakyapuri', ' Select Citywalk Mall',
       ' Hauz Khas Village', ' Ambience Mall', ' DLF Mall of India',
       ' M Block Market', ' Pandara Road Market', ' Mehrauli',
       ' Chandni Chowk', ' The Claridges', ' Anand Vihar',
       ' Delhi University-GTB Nagar', ' Geetanjali Enclave',
       ' Greater Kailash 2 (GK2)', '  32nd Avenue', ' Sector 29',
       ' Pacific Mall', ' Sector 41', ' Global Foyer Mall', ' The Oberoi',
       ' Saket', ' Baani Square', ' Hajipur', ' Sushant Lok',
       ' Subhash Nagar', ' Majnu ka Tila', ' Vasant Vihar',
       ' Greater Kailash 1 (GK1)', ' Aerocity', ' The Roseate',
       ' Worldmark 1', ' MGF Metropolis Mall', ' Jama Masjid',
       ' Golf Course Road', ' South Point Mall', ' Sector 23',
       ' Suncity Business Tower', ' JW Marriott New Delhi',
       ' Unity One Mall', ' Cross Point Mall', ' Sohna Road',
       ' Sector 110', ' DLF Avenue', ' Safdarjung', ' Sangam Courtyard',
       ' Pullman New Delhi Aerocity', ' DLF Galleria', ' Satyaniketan',
       ' Supermart 1', ' Radisson Blu Plaza Delhi Airport',
       ' Eros City Square Mall', ' Raheja Mall', ' Lawrence Road',
       ' Chhatarpur', ' Karkardooma', " Shangri-La's - Eros Hotel",
       ' Janpath', ' Elements One Mall', ' Vasant Kunj',
       ' Defence Colony', ' The Leela Ambience', ' Feroze Shah Road',
       ' Punjabi Bagh', ' Hauz Khas', ' Ashok Vihar Phase 2',
       ' Mandi House', ' Jasola', ' Sector 49',
       ' Country Inn & Suites by Carlson', ' Andaz Delhi',
       ' Indirapuram Habitat Centre', ' Rajouri Garden',
       ' Ansal Plaza Mall', ' Sector 16', ' MG Road',
       ' The Taj Mahal Hotel', ' Paschim Vihar', ' Indirapuram',
       ' Clarens Hotel', ' Sector 14', ' R K Puram', ' Sector 63',
       ' Ardee City', ' Hyatt Regency', ' Sector 72', ' Kasbah',
       ' Shahpur Jat', ' Sector 56', ' DLF Phase 1', ' Shopping Mall',
       ' Bhikaji Cama Place', ' Green Park', ' Civil Lines',
       ' Epicuria Food Mall', ' Chanakya Mall', ' South City 2',
       ' Preet Vihar', ' Sector 81', ' The Colonnade',
       ' Gardens Galleria', ' Logix City Centre', ' Sector 12',
       ' Prashant Vihar', ' Essex Farms', ' Sector 62', ' Sector 50',
       ' Knowledge Park', ' Taj Palace', ' Rajinder Nagar',
       ' Nehru Place', ' Raj Nagar', ' Lajpat Nagar 2', ' Sector 135',
       ' Mayur Vihar Phase 1', ' Sector 5', ' Defence Colony Main Market',
       ' Central Arcade', ' East of Kailash', ' Sector 10',
       ' Sheraton New Delhi Hotel', ' Udyog Vihar', ' South Extension 2',
       ' Sikandarpur', ' Crowne Plaza Hotel', ' Champa Gali',
       ' Greater Kailash 3 (GK3)', ' Rohini', ' DLF Phase 5',
       ' Sarojini Nagar', ' Brahmaputra Shopping Complex', ' Holiday Inn',
       ' Vivanta by Taj', ' The Westin Gurgaon', ' PVR Anupam Complex',
       ' Sector 18', ' Sector 93', ' SDA Market', ' Geeta Colony',
       ' Sector 13', ' Roseate House', ' Moti Nagar', ' City Centre Mall',
       ' Sector 9', " 3C's Mall", ' The Leela Palace', ' Janakpuri',
       ' East Patel Nagar', ' One Horizon Center', ' Sector 83',
       ' DLF Phase 3', ' Pitampura', ' Sunder Nagar', ' Munirka',
       ' Sector 4', ' The Imperial', ' Ambassador', ' Sector 31',
       ' Nirvana Courtyard', ' Uttam Nagar', ' Trident', ' NIT',
       ' Community Centre', ' DLF Phase 4', ' Karol Bagh',
       ' Crossing Republik', ' Novotel New Delhi Aerocity',
       ' Tughlakabad Institutional Area', ' New Friends Colony',
       ' Gaur City 1', ' Flyover Market', ' Southern Park Mall',
       ' Central Plaza Mall', ' Sector 7', ' Alaknanda',
       ' Taj City Centre Gurugram', ' Kamla Nagar', ' Sector 11',
       ' Qutab Plaza', ' Sector 39', ' Kaushambi', ' Rodeo Drive', ' JNU',
       ' Radisson Blu', ' Sainik Farms', ' Malviya Nagar',
       ' Pandav Nagar', ' Yusuf Sarai', ' Jaypee Siddharth', ' Sector 57',
       ' Sector 25', ' Kirti Nagar', ' The Park', ' Murthal',
       ' Netaji Subhash Place', ' Lado Sarai', ' Jail Road',
       ' Supertech Shopprix Mall', ' Hudson Lane', ' DLF Promenade Mall',
       ' Kalkaji', ' India Gate', ' Rajendra Place', ' Radisson',
       ' Adchini', ' The Lalit New Delhi', ' Lajpat Nagar 3',
       ' Le Meridien Gurgaon', ' Sadar Bazar', ' Crowne Plaza',
       ' Chittaranjan Park', ' Vaishali', ' Shahdara', ' Uday Park',
       ' Asaf Ali Road', ' Sector 30', ' Amrapali Leisure Valley',
       ' Nizamuddin', ' Courtyard by Marriott', ' Ballabhgarh',
       ' Paharganj', ' Shalimar Bagh', ' Hotel City Park',
       ' DLF Cyber City', ' Gamma 1', ' Daryaganj', ' Sector 52',
       ' The Great India Place', ' Sector 21', ' Park Ascent',
       ' Amrapali Dream Valley', ' Sector 17', ' Jangpura',
       ' Chander Nagar', ' Vikaspuri', ' Gaur City 2', ' Panchsheel Park',
       ' Sector 37', ' Model Town 2', ' Alpha 2', ' Lajpat Nagar 4',
       ' Omaxe Connaught Place', ' Mayur Vihar Phase 2',
       ' Sushant Shopping Arcade', ' Vivek Vihar', ' Sector 45',
       ' Sector 71', ' DLF Phase 2', ' Gujranwala Town', ' Sector 54',
       ' Amar Colony', ' Golf Course Extension', ' Okhla Phase 3',
       ' Laxmi Nagar', ' West Patel Nagar', ' The Lodhi',
       ' Radisson Gurugram Sohna Road City Center',
       ' Vibe by The LaLit Traveller', ' Gole Market',
       ' Old Railway Road', ' Aggarwal City Mall', ' Aditya City Centre',
       ' Le Meridien', ' Nehru Nagar',
       ' Sandal Suites By Lemon Tree Hotels',
       ' The Leela Ambience Convention Hotel', ' INA',
       ' Radisson Blu Faridabad', ' Charmwood Village',
       ' Basant Lok Market', ' Sector 22', ' Gwal Pahari',
       ' Sheikh Sarai', ' Jaipuria Sunrise Plaza', ' Barakhamba Road',
       ' Cross River Mall', ' Sector PI', ' Global Foyer',
       ' Crescent Square Mall', ' Palam Vihar', ' Living Style Mall',
       ' Mahipalpur', ' Sector 132', ' Gaur Central  Mall',
       ' Hyatt Place Gurgaon', ' PVR City Centre Mall', ' Narela',
       ' MGF Metropolitan Mall', ' Mayapuri Phase 2', ' Sector 53',
       ' The India Mall', ' Supermart 2', ' Sector 19', ' Ameya Suites',
       ' WelcomHotel Dwarka', ' Sector 6', ' Sector 43',
       ' Ninex City Mart Mall', ' Eros Hotel', ' Kingdom of Dreams',
       ' Kavi Nagar', ' Ashok Vihar Phase 1', ' Ashok Vihar Phase 3',
       ' Palam', ' Vyapar Kendra', ' Meharchand Market', ' Shastri Nagar',
       ' Spice World Mall', ' Najafgarh', ' Omega 2',
       ' Pride Plaza Hotel', ' Ardee Mall', ' IP Extension',
       ' Krishna Nagar', ' Good Earth City Center', ' Tilak Nagar',
       ' Hotel Alka Classic', ' The Umrao', ' Shakarpur', ' Zakir Nagar',
       ' Hilton Garden Inn', ' ibis New Delhi', ' Hong Kong Bazaar Mall',
       ' V3S Mall', ' Vivanta New Delhi', ' Patparganj', ' Badkal Lake',
       ' Sector 44', ' Badarpur Border', ' Vasant Square Mall',
       ' Vasundhara', ' Karampura', ' South Extension 1', ' Mathura Road',
       ' Crown Plaza Mall', ' Mukherjee Nagar', ' Tagore Garden',
       ' Azadpur', ' Sector 86', ' The Ashok', ' Sector 27', ' Sector 35',
       ' Jaypee Greens Golf & Spa Resort', ' Park Inn by Radisson',
       ' MSX Mall', ' Omaxe Gurgaon Mall', ' Model Town 3', ' Beta 1',
       ' Jaipuria Plaza', ' South City 1', ' Dilli Haat', ' Harsha Mall',
       ' Naraina', ' Panchsheel Square Mall', ' Sector 28',
       ' Parliament Street', ' Khel Gaon Marg', ' Worldmark 3',
       ' Starling Mall', ' DLF Emporio Mall', ' Radisson Blu Hotel',
       ' Yashwant Place Commercial Complex', ' Model Town 1', ' Aloft',
       ' Vikas Marg', ' Ambedkar Road', ' SDA', ' Lajpat Nagar 1',
       ' Ramada Gurgaon Central', ' Loni', ' Dia Park Premier',
       ' The Grand New Delhi', ' Raja Garden', ' The Grand Venice Mall',
       ' Chi 4', ' Spark Mall', ' Central Market',
       ' Crown Interiorz Mall', ' The Sapphire Mall',
       ' The Suryaa New Delhi', ' Durga Puri', ' Dilshad Garden']